### ISSUE TITLE
可以写个使用说明吗

### ISSUE THREAD

**Issue by wodog** [LiangCY/MovieTickets#1]
换了db后没有影院的电影的数据呀

**Comment by LiangCY** [comment]
- 电影和票价的数据是每天固定时间爬取的，你可以直接调用 scraper/movie.js 中的 updateMovies 方法获取电影数据。
- 因为影院名称在各平台都不太相同，所以需要手动添加哦。开启网站后在http://localhost:3030/cinemas/manage 页面中添加即可。
