### ISSUE TITLE
我想知道,在不同的页面之下,怎么去核对

### ISSUE THREAD

**Issue by Joursion** [LiangCY/MovieTickets#3]
比如我在taobao上是显示着 <大圣归来>  nuomi上显示着  <西游记之大圣归来>  最后要怎么合并,或者说怎么去解决这样的不同呢....

**Comment by LiangCY** [comment]
这确实是个问题，之前我也发现了，”寻龙诀“一直没有百度糯米的票价，然后看了数据库里确实也没有”寻龙诀“的糯米id，然后发现糯米里面叫做”鬼吹灯之寻龙诀“。这种我也没有好的解决办法，只能手动在代码里加上判断，在获取到电影名称后，进行判断再修改名称，比如在获取糯米的电影的id时，如果名称是”鬼吹灯之寻龙诀“的话，就把name赋值为”寻龙诀“。总之就是加上特例的判断吧。
